---
- name: EDA testing - eenvoudig debug alert
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Print success boodschap
      ansible.builtin.debug:
        msg: "EDA rulebook connectie werkt 100% ...."
    
    - name: Log tijd
      ansible.builtin.debug:
        msg: "Uitgevoerd op {{ lookup('pipe', 'date') }}"
